channels:
  - defaults
  - conda-forge
dependencies:
  - conda-forge::fire
  - conda-forge::flask-socketio>=5.3.2 # covasim
  - conda-forge::ncurses # fixes: libtinfo.so.6: no version information available (required by bash)
  - conda-forge::python-igraph
  - conda-forge::statsmodels
  - fire
  - gcc_linux-64 # covasim
  - gunicorn
  - ipywidgets
  - libgcc-ng
  - matplotlib
  - networkx
  - notebook
  - numba
  - numpy
  - pandas
  - plotly
  - python # >=3.10 introduces problems with libgcc-ng deps
  - scikit-learn<=0.24.1
  - scipy
  - twisted # covasim
  - werkzeug<=2.0.1 # covasim, WONTFIX - do NOT upgrade further, otherwise covasim webapp will fail
  - pip
  - pip:
    - scirisweb>=0.17.0
    - sciris>=2.0.4